### PR TITLE
nanoauth has the X-NANOBOX-TOKEN header as the default

### PR DESCRIPTION
**Pull request by iamthemuffinman**
Seen [here](https://github.com/nanobox-io/golang-nanoauth/blob/master/nanoauth.go#L19)

### CODE REVIEW

**Comment by tylerflint** [comment]
@iamthemuffinman You're right, thanks for this! 

@glinton When you get a minute, can you review/merge this?

**Comment by iamthemuffinman** [comment]
@tylerflint You're welcome! Probably the smallest PR ever. :)

**Comment by iamthemuffinman** [comment]
@glinton Did you have a chance to review this?

**Comment by glinton** [comment]
@iamthemuffinman, sorry for the delay, I have reviewd it. I've just been debating whether to keep `x-nanobox-token` or go with the more generic `x-admin-token` that [logvac](https://github.com/nanopack/logvac/blob/master/api/api.go#L40) implements. I'll go ahead and merge this in for now and change it when/if I finally decide. Thanks

**Comment by iamthemuffinman** [comment]
@glinton No problem! Thanks!

**Pull request merged**
